name: accom_daemon
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  lints: ^1.0.0
dependencies: 
  dbus: ^0.7.1
  desktop_notifications: ^0.6.1
  encrypt: ^5.0.1
  glob: ^2.0.2
  http: ^0.13.4
  image: ^3.0.8
  intl: ^0.17.0
  json_annotation: ^4.3.0
  logging: ^1.0.2
  path: ^1.8.0
  process: ^4.2.4
  xdg_directories: ^0.2.0
